name: Reusable workflow

on:
  workflow_call:
    inputs:
      input_one:
        required: true
        type: string

jobs:
  do_thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.action_repository }}
      - run: echo ${{ inputs.input_one }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      # - uses: qoomon/actions--context@v2
      #   name: Get environment name as var
      #   id: context

      - run: yarn --immutable

      - uses: ./scripts/workflows/verify-web-artifacts
        with:
          allowedWebBranches: ${{ vars.ALLOWED_WEB_BRANCHES }}
          artifactInfo: ${{ inputs.input_one }}
